runtime: python310
entrypoint: gunicorn -b :$PORT app:app

# Instance class (optional, for scaling)
instance_class: F2

# Automatic scaling
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

# Handlers for static files (optional)
handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto

service_account: sa-translator-subtitles@satranslatorcontenttool.iam.gserviceaccount.com

env_variables:
  FLASK_ENV: "production"
  GOOGLE_CLOUD_PROJECT: "satranslatorcontenttool"